version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run:
          name: get dependencies for running tests and multi-architecture compilation
          command: |
            mkdir -p $TEST_RESULTS
            go get github.com/jstemmer/go-junit-report
            git branch -u origin ${CIRCLE_BRANCH}
            go get -u
            go get github.com/mitchellh/gox
            go get github.com/tcnksm/ghr
      - run:
          name: Run Unit Tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out
          
      - run:
          name: Build snippetbox binary and publish it to github as a release
          command: |
            make build
            make publish